#!/usr/bin/env bash
#
# setting up git

cd "$(dirname "$0")"
. ../resources/functions
get_sudo

h1 "setting up git"

# link files
install_dotfiles

# set up git-cred-helper
make -C /usr/share/doc/git/contrib/credential/libsecret
