#!/usr/bin/env bash
#
# setting up git

cd "$(dirname "$0")"
. ../resources/functions
get_sudo


h1 "setting up git"

install_dotfiles
install_packages

# set up git-cred-helper
sudo make -C /usr/share/doc/git/contrib/credential/libsecret
