#!/usr/bin/env bash
#
# install all WSL sections

dir="$(dirname $(readlink -f "$0"))"

cd ${dir}
source ./resources/functions/main

get_sudo
title

# link bashrc
h2 "installing bash profile"
link_file ${dir}/.bashrc ${HOME}
source ${HOME}/.bashrc

# mount a drive
sudo mkdir /mnt/a
sudo mount -t drvfs A: /mnt/a

# link Windows drives to home
ln -s /mnt/c/Users/uktre02/ ${HOME}/winhome
ln -s /mnt/c/Users/uktre02/Box\ Sync/ ${HOME}/box

ln -s /mnt/c/Users/uktre02/dev ${HOME}/dev
ln -s /mnt/c/Users/uktre02/Box\ Sync/CI/analysis ${HOME}/analysis

ln -s /mnt/a/TomRea/.aws ${HOME}/.aws

# upgrade and run setup
update_sys
bash ./git/install
bash ./python/install
bash ./node/install

# r setup
mkdir -p ~/winhome/.R/library
mkdir -p ~/winhome/.R/snippets

cp ./r/.Rprofile ~/winhome/
cp ./r/.Renviron ~/winhome/

cp ./r/r.snippets ~/winhome/.R/snippets