#!/usr/bin/env bash
#
# install all sections

cd "$(dirname "$0")"
source ./resources/functions/main

get_sudo
title

# link bashrc
h2 "installing bash profile"
link_file .bashrc ${HOME}
source ${HOME}/.bashrc

# upgrade and run setup
update_sys
run install
