#!/usr/bin/env bash
#
# Run all WSL dotfile installers

cd "$(dirname "$0")"
. ./resources/functions
get_sudo


title

sudo mkdir /mnt/a
sudo mount -t drvfs A: /mnt/a

ln -s /mnt/c/Users/uktre02/ ${HOME}/winhome
ln -s /mnt/c/Users/uktre02/dev ${HOME}/dev
ln -s /mnt/c/Users/uktre02/Box\ Sync/CI ${HOME}/ci
ln -s /mnt/a/TomRea/.aws ${HOME}/.aws

update_sys
run install_wsl

source ${HOME}/.bashrc
