#!/usr/bin/env bash
#
# install all sections

dir = "$(dirname $(readlink -f "$0"))"

cd ${dir}
source ./resources/functions/main

get_sudo
title

# link bashrc
h2 "installing bash profile"
link_file ${dir}/.bashrc ${HOME}
source ${HOME}/.bashrc

# upgrade and run setup
update_sys
run install
