#!/usr/bin/env bash
#
# Run all dotfile installers

cd "$(dirname "$0")"
. ./resources/functions
get_sudo


title

# link bashrc
mv ${HOME}/.bashrc ${HOME}/.bashrc.backup
ln -s ${PWD}/.bashrc.symlink ${HOME}/.bashrc

update_sys
run install

source ${HOME}/.bashrc
