#!/usr/bin/env bash
#
# setting up insync

cd "$(dirname "$0")"
. ../resources/functions
get_sudo


h1 "setting up insync"

add_reps
install_packages

# turn appindicator on
# https://pop.system76.com/docs/status-icons/
# `gnome-shell-extension-tool` doesn't seem to work
# use `gnome-shell-extension-prefs` and turn on manually
# gnome-shell-extension-tool -e ubuntu-appindicator
