#!/usr/bin/env bash
#
# setting up docker

cd "$(dirname "$0")"
. ../resources/functions
get_sudo


h1 "setting up docker"

add_reps
install_packages

# add user to docker group
# requires reboot
sudo usermod -aG docker ${USER}
