#!/usr/bin/env bash
#
# post install script

# add user to docker group
# requires reboot
sudo usermod -aG docker ${USER}

# install docker compose
# https://docs.docker.com/compose/install/
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
