#!/usr/bin/env bash
#
# setting up system settings

cd "$(dirname "$0")"
. ../resources/functions
get_sudo

h1 "setting up system settings"
info "empty"

# enable tap-to-click
# gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true

# switch scroll direction
#
#
