#!/usr/bin/env bash
#
# setting up system settings
#
# TODO:
# create function to find and run all settings scipts

cd "$(dirname "$0")"
. ../resources/functions
get_sudo


h1 "setting up system settings"

bash ./touchpad.settings
