#!/usr/bin/env bash
#
# setting up atom

cd "$(dirname "$0")"
. ../resources/functions
get_sudo


h1 "setting up atom"

add_reps
install_packages
install_dotfiles "${HOME}/.atom"

# install atom packages
h2 "installing atom packages"
apm i --packages-file package.atom.list
