#!/usr/bin/env bash
#
# setting up r
#
# TODO:
# param download.list & rep?

cd "$(dirname "$0")"
. ../resources/functions
get_sudo


h1 "setting up r"

# create dir to hold r packages
mkdir -p ~/R/library

install_dotfiles
add_reps
install_packages
dl_deb
install_deb

# install r packages
h2 "installing r packages"
info "installing"
Rscript package.install &>> log &&
  success "done" || fail "faild"
