#!/usr/bin/env bash
#
# pre install script

source ../resources/functions/main 

# create dir to hold r packages
h2 "creating r package dir"

pkg_dir=${HOME}/.R/library

info ${pkg_dir}
mkdir -p ${pkg_dir} && success ${pkg_dir} || fail ${pkg_dir}
